export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";

export const CATEGORY_PRODUCT_REQUEST = "CATEGORY_PRODUCT_REQUEST";
export const CATEGORY_PRODUCT_SUCCESS = "CATEGORY_PRODUCT_SUCCESS";
export const CATEGORY_PRODUCT_FAIL = "CATEGORY_PRODUCT_FAIL";

export const CATEGORY_DETAIL_REQUEST = "CATEGORY_DETAIL_REQUEST";
export const CATEGORY_DETAIL_SUCCESS = "CATEGORY_DETAIL_SUCCESS";
export const CATEGORY_DETAIL_FAIL = "CATEGORY_DETAIL_FAIL";

export const UPDATE_DETAIL_REQUEST = "UPDATE_DETAIL_REQUEST";
export const UPDATE_DETAIL_SUCCESS = "UPDATE_DETAIL_SUCCESS";
export const UPDATE_DETAIL_FAIL = "UPDATE_DETAIL_FAIL";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL = "CATEGORY_DELETE_FAIL";
